apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
    flux.weave.works/antecedent: devops:helmrelease/nexus
  creationTimestamp: "2018-07-11T14:59:48Z"
  generation: 40
  labels:
    app: sonatype-nexus
    chart: sonatype-nexus-1.5.1
    fullname: digimind-nexus-sonatype-nexus
    heritage: Tiller
    release: digimind-nexus
  name: digimind-nexus-sonatype-nexus
  namespace: devops
  resourceVersion: "225528651"
  selfLink: /apis/extensions/v1beta1/namespaces/devops/deployments/digimind-nexus-sonatype-nexus
  uid: 0e785c31-851b-11e8-a488-fa163eb1a314
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonatype-nexus
      release: digimind-nexus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonatype-nexus
        release: digimind-nexus
    spec:
      containers:
      - env:
        - name: install4jAddVmParams
          value: -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap
        image: quay.io/travelaudience/docker-nexus:3.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 250
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: nexus
        ports:
        - containerPort: 5003
          name: nexus-docker-g
          protocol: TCP
        - containerPort: 8081
          name: nexus-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 4800Mi
          requests:
            cpu: 50m
            memory: 4800Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
        - mountPath: /nexus-data/backup
          name: nexus-backup
      - env:
        - name: ALLOWED_USER_AGENTS_ON_ROOT_REGEX
          value: GoogleHC
        - name: CLOUD_IAM_AUTH_ENABLED
          value: "false"
        - name: BIND_PORT
          value: "8080"
        - name: ENFORCE_HTTPS
          value: "true"
        - name: NEXUS_DOCKER_HOST
          value: dcr.digimind.tech
        - name: NEXUS_HTTP_HOST
          value: nexus.digimind.tech
        - name: UPSTREAM_DOCKER_PORT
          value: "5003"
        - name: UPSTREAM_HTTP_PORT
          value: "8081"
        - name: UPSTREAM_HOST
          value: localhost
        image: quay.io/travelaudience/docker-nexus-proxy:2.1.0
        imagePullPolicy: IfNotPresent
        name: nexus-proxy
        ports:
        - containerPort: 8080
          name: nexus-proxy
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: digimind-nexus-sonatype-nexus-data
      - emptyDir: {}
        name: nexus-backup
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-20T08:28:02Z"
    lastUpdateTime: "2020-03-10T14:34:40Z"
    message: ReplicaSet "digimind-nexus-sonatype-nexus-869cb5d9cd" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-09T13:25:02Z"
    lastUpdateTime: "2020-04-09T13:25:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 40
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
