apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2018-08-23T09:16:21Z"
  generation: 1
  labels:
    app: digimind-sonarqube-postgresql
    chart: postgresql-0.8.3
    heritage: Tiller
    release: digimind-sonarqube
  name: digimind-sonarqube-postgresql
  namespace: devops
  resourceVersion: "228151695"
  selfLink: /apis/extensions/v1beta1/namespaces/devops/deployments/digimind-sonarqube-postgresql
  uid: 33831df5-a6b5-11e8-8e3b-fa163eb1a314
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: digimind-sonarqube-postgresql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: digimind-sonarqube-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: sonarUser
        - name: PGUSER
          value: sonarUser
        - name: POSTGRES_DB
          value: sonarDB
        - name: POSTGRES_INITDB_ARGS
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: digimind-sonarqube-postgresql
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: postgres:9.6.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: digimind-sonarqube-postgresql
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: data
          subPath: postgresql-db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: digimind-sonarqube-postgresql
status:
  conditions:
  - lastTransitionTime: "2018-08-23T09:16:21Z"
    lastUpdateTime: "2018-08-23T09:16:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2018-08-23T09:16:21Z"
    lastUpdateTime: "2018-08-23T09:16:43Z"
    message: ReplicaSet "digimind-sonarqube-postgresql-6566c4f54f" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
