apiVersion: v1
data:
  postgres-password: cjJoQTlGbXBwRHhtUjJ3TA==
kind: Secret
metadata:
  creationTimestamp: "2018-08-23T09:16:21Z"
  labels:
    app: digimind-sonarqube-postgresql
    chart: postgresql-0.8.3
    heritage: Tiller
    release: digimind-sonarqube
  name: digimind-sonarqube-postgresql
  namespace: devops
  resourceVersion: "12154747"
  selfLink: /api/v1/namespaces/devops/secrets/digimind-sonarqube-postgresql
  uid: 33727107-a6b5-11e8-8e3b-fa163eb1a314
type: Opaque
